import type { Pegawai, StatistikDashboard } from "./types"

export const mockPegawai: Pegawai[] = [
  {
    nipPegawai: "198501152010011001",
    nama: "Dr. Suhendra, S.H., M.H.",
    gelarDepan: "Dr.",
    gelarBelakang: "S.H., M.H.",
    jabatan: "Kepala Dinas",
    departemen: "KEPALA DINAS",
    golongan: "Pembina Utama Muda (IV/c)",
    status: "Aktif",
    tanggalMasuk: "2010-01-15",
    email: "suhendra@samarindakota.go.id",
    noHp: "081234567890",
    tempatLahir: "Samarinda",
    tanggalLahir: "1985-01-15",
    jenisKelamin: "Laki-laki",
    agama: "Islam",
    alamat: "Jl. Pahlawan No. 1",
    identitasResmi: {
      nipIdResmi: "198501152010011001",
      nik: "6401011501850001",
      noBpjs: "9876543210123456",
      noNpwp: "12.345.678.9-012.345",
      karpeg: "K-2010/001",
      karsuKarsi: "KK-2010/001",
      taspen: "T-2010/001",
    },
    kepegawaian: {
      nipKepegawaian: "198501152010011001",
      statusPegawai: "PNS",
      jenisPegawai: "Tenaga Struktural",
      tmtCpns: "2010-01-15",
      tmtPns: "2012-01-15",
      masaKerjaTahun: 14,
      masaKerjaBulan: 2,
    },
    riwayatPangkat: [
      {
        idRiwayat: 1,
        nipRiwayat: "198501152010011001",
        idPangkatRiwayat: 1,
        tmtPangkat: "2010-01-15",
        tmtSelesai: "2015-01-15",
        status: "Selesai",
        pangkat: {
          idPangkat: 1,
          namaPangkat: "Penata Muda (III/a)",
        },
      },
      {
        idRiwayat: 2,
        nipRiwayat: "198501152010011001",
        idPangkatRiwayat: 2,
        tmtPangkat: "2015-01-15",
        tmtSelesai: "2019-01-15",
        status: "Selesai",
        pangkat: {
          idPangkat: 2,
          namaPangkat: "Penata Tingkat I (III/d)",
        },
      },
      {
        idRiwayat: 3,
        nipRiwayat: "198501152010011001",
        idPangkatRiwayat: 3,
        tmtPangkat: "2019-01-15",
        tmtSelesai: undefined,
        status: "Berlaku",
        pangkat: {
          idPangkat: 3,
          namaPangkat: "Pembina Utama Muda (IV/c)",
        },
      },
    ],
    efiles: [
      {
        idFile: 1,
        nipEfile: "198501152010011001",
        jenisDokumen: "SK PENGANGKATAN",
        namaFile: "SK_Pengangkatan_PNS_2010.pdf",
        filePath: "/documents/sk_pns_2010.pdf",
        waktuUpload: "2024-01-15",
      },
      {
        idFile: 2,
        nipEfile: "198501152010011001",
        jenisDokumen: "SERTIFIKAT PENDIDIKAN",
        namaFile: "Sertifikat_S1_Hukum.pdf",
        filePath: "/documents/sertifikat_s1.pdf",
        waktuUpload: "2024-01-16",
      },
    ],
  },
  {
    nipPegawai: "199003202015022002",
    nama: "Siti Nurhaliza, S.Adm.",
    gelarBelakang: "S.Adm.",
    jabatan: "Kepala Bidang Pelayanan Pendaftaran Penduduk",
    departemen: "Pelayanan Pendaftaran Penduduk",
    golongan: "Pembina (IV/a)",
    status: "Aktif",
    tanggalMasuk: "2015-02-20",
    email: "siti.nurhaliza@samarindakota.go.id",
    noHp: "081234567891",
    tempatLahir: "Balikpapan",
    tanggalLahir: "1990-03-20",
    jenisKelamin: "Perempuan",
    agama: "Islam",
    alamat: "Jl. Sudirman No. 45",
    identitasResmi: {
      nipIdResmi: "199003202015022002",
      nik: "6402023201900001",
      noBpjs: "9876543210123457",
      noNpwp: "12.345.678.9-012.346",
      karpeg: "K-2015/002",
      karsuKarsi: "KK-2015/002",
      taspen: "T-2015/002",
    },
    kepegawaian: {
      nipKepegawaian: "199003202015022002",
      statusPegawai: "PNS",
      jenisPegawai: "Tenaga Fungsional",
      tmtCpns: "2015-02-20",
      tmtPns: "2017-02-20",
      masaKerjaTahun: 9,
      masaKerjaBulan: 0,
    },
    riwayatPangkat: [
      {
        idRiwayat: 4,
        nipRiwayat: "199003202015022002",
        idPangkatRiwayat: 4,
        tmtPangkat: "2015-02-20",
        tmtSelesai: "2020-02-20",
        status: "Selesai",
        pangkat: {
          idPangkat: 4,
          namaPangkat: "Penata Muda Tingkat I (III/b)",
        },
      },
      {
        idRiwayat: 5,
        nipRiwayat: "199003202015022002",
        idPangkatRiwayat: 5,
        tmtPangkat: "2020-02-20",
        tmtSelesai: undefined,
        status: "Berlaku",
        pangkat: {
          idPangkat: 5,
          namaPangkat: "Pembina (IV/a)",
        },
      },
    ],
    efiles: [
      {
        idFile: 3,
        nipEfile: "199003202015022002",
        jenisDokumen: "SK PENGANGKATAN",
        namaFile: "SK_Pengangkatan_PNS_2015.pdf",
        filePath: "/documents/sk_pns_2015.pdf",
        waktuUpload: "2024-02-10",
      },
    ],
  },
  {
    nipPegawai: "198708102012031003",
    nama: "Bayu Pratama Putra, S.Adm.",
    gelarBelakang: "S.Adm.",
    jabatan: "Staff Pelayanan Pencatatan Sipil",
    departemen: "Pelayanan Pencatatan Sipil",
    golongan: "Penata Muda (III/a)",
    status: "Aktif",
    tanggalMasuk: "2012-03-10",
    email: "bayu.pratama@samarindakota.go.id",
    noHp: "081234567892",
    tempatLahir: "Tenggarong",
    tanggalLahir: "1987-08-10",
    jenisKelamin: "Laki-laki",
    agama: "Islam",
    alamat: "Jl. Mulawarman No. 12",
  },
  {
    nipPegawai: "199205152018044004",
    nama: "Rahmawati Dayak, S.Adm.",
    gelarBelakang: "S.Adm.",
    jabatan: "Kepala Bidang Pengelolaan Informasi Administrasi Kependudukan",
    departemen: "Pengelolaan Informasi Administrasi Kependudukan",
    golongan: "Penata Tingkat I (III/d)",
    status: "Cuti",
    tanggalMasuk: "2018-04-15",
    email: "rahmawati.d@samarindakota.go.id",
    noHp: "081234567893",
    tempatLahir: "Bontang",
    tanggalLahir: "1992-05-15",
    jenisKelamin: "Perempuan",
    agama: "Islam",
    alamat: "Jl. Awang Long No. 88",
  },
  {
    nipPegawai: "197506202000015005",
    nama: "Hendra Kusuma, S.Adm.",
    gelarBelakang: "S.Adm.",
    jabatan: "Staff Pelayanan Pendaftaran Penduduk",
    departemen: "Pelayanan Pendaftaran Penduduk",
    golongan: "Pengatur Tingkat I (II/d)",
    status: "Aktif",
    tanggalMasuk: "2000-01-20",
    email: "hendra.kusuma@samarindakota.go.id",
    noHp: "081234567894",
    tempatLahir: "Samarinda",
    tanggalLahir: "1975-06-20",
    jenisKelamin: "Laki-laki",
    agama: "Islam",
    alamat: "Jl. Juanda No. 20",
  },
  {
    nipPegawai: "196508101990016006",
    nama: "Abdul Rahman, S.H.",
    gelarBelakang: "S.H.",
    jabatan: "Kepala Bidang Pelayanan Pencatatan Sipil",
    departemen: "Pelayanan Pencatatan Sipil",
    golongan: "Pembina (IV/a)",
    status: "Aktif",
    tanggalMasuk: "1990-01-10",
    email: "abdul.rahman@samarindakota.go.id",
    noHp: "081234567895",
    tempatLahir: "Berau",
    tanggalLahir: "1965-08-10",
    jenisKelamin: "Laki-laki",
    agama: "Islam",
    alamat: "Jl. Gajah Mada No. 5",
  },
  {
    nipPegawai: "199408152020017007",
    nama: "Rina Melati Sari, S.Adm.",
    gelarBelakang: "S.Adm.",
    jabatan: "Kepala Bidang Pemanfaatan Data dan Inovasi Pelayanan",
    departemen: "Pemanfaatan Data dan Inovasi Pelayanan",
    golongan: "Penata (III/c)",
    status: "Aktif",
    tanggalMasuk: "2023-01-15",
    email: "rina.melati@samarindakota.go.id",
    noHp: "081234567896",
    tempatLahir: "Samarinda",
    tanggalLahir: "1994-08-15",
    jenisKelamin: "Perempuan",
    agama: "Islam",
    alamat: "Jl. Antasari No. 33",
  },
  {
    nipPegawai: "198912102014018008",
    nama: "Fajar Borneo, S.Adm.",
    gelarBelakang: "S.Adm.",
    jabatan: "Staff Pengelolaan Informasi Administrasi Kependudukan",
    departemen: "Pengelolaan Informasi Administrasi Kependudukan",
    golongan: "Pengatur Muda Tingkat I (II/b)",
    status: "Aktif",
    tanggalMasuk: "2014-01-10",
    email: "fajar.borneo@samarindakota.go.id",
    noHp: "081234567897",
    tempatLahir: "Kutai Barat",
    tanggalLahir: "1989-12-10",
    jenisKelamin: "Laki-laki",
    agama: "Kristen",
    alamat: "Jl. Cendana No. 7",
  },
  {
    nipPegawai: "199106152019019009",
    nama: "Dian Permata Kutai, S.Adm.",
    gelarBelakang: "S.Adm.",
    jabatan: "Kepala Subbagian Keuangan",
    departemen: "Kasubag. Keuangan",
    golongan: "Penata (III/c)",
    status: "Aktif",
    tanggalMasuk: "2022-06-15",
    email: "dian.permata@samarindakota.go.id",
    noHp: "081234567898",
    tempatLahir: "Kutai Kartanegara",
    tanggalLahir: "1991-06-15",
    jenisKelamin: "Perempuan",
    agama: "Islam",
    alamat: "Jl. Diponegoro No. 100",
  },
  {
    nipPegawai: "198803102016010010",
    nama: "Agus Mahakam, S.Adm.",
    gelarBelakang: "S.Adm.",
    jabatan: "Kepala Subbagian Umum dan Kepegawaian",
    departemen: "Kasubag Umum dan Kepegawaian",
    golongan: "Penata (III/c)",
    status: "Aktif",
    tanggalMasuk: "2016-01-10",
    email: "agus.mahakam@samarindakota.go.id",
    noHp: "081234567899",
    tempatLahir: "Samarinda",
    tanggalLahir: "1988-03-10",
    jenisKelamin: "Laki-laki",
    agama: "Islam",
    alamat: "Jl. Siradj Salman No. 55",
  },
]

export const mockStatistik: StatistikDashboard = {
  totalPegawai: 156,
  totalDokumen: 423,
  pegawaiAktif: 142,
  pegawaiCuti: 8,
  updateTerbaru: [
    {
      id: "u1",
      aksi: "Dokumen Diunggah",
      detail: "SK Kenaikan Pangkat untuk Hendra Kusuma",
      waktu: "5 menit yang lalu",
      user: "Admin",
    },
    {
      id: "u2",
      aksi: "Data Diperbarui",
      detail: "Update status Rahmawati Dayak menjadi Cuti",
      waktu: "1 jam yang lalu",
      user: "Admin",
    },
    {
      id: "u3",
      aksi: "Pegawai Baru",
      detail: "Rina Melati Sari ditambahkan ke departemen IT",
      waktu: "2 jam yang lalu",
      user: "Admin",
    },
    {
      id: "u4",
      aksi: "Dokumen Diunggah",
      detail: "Sertifikat Pelatihan IT untuk Bayu Pratama",
      waktu: "3 jam yang lalu",
      user: "Admin",
    },
    {
      id: "u5",
      aksi: "Data Diperbarui",
      detail: "Update jabatan Muhammad Iqbal Fadillah",
      waktu: "1 hari yang lalu",
      user: "Admin",
    },
  ],
}

export const departemenList = [
  "Semua",
  "KEPALA DINAS",
  "Pelayanan Pendaftaran Penduduk",
  "Pelayanan Pencatatan Sipil",
  "Pengelolaan Informasi Administrasi Kependudukan",
  "Pemanfaatan Data dan Inovasi Pelayanan",
  "Kasubag Umum dan Kepegawaian",
  "Kasubag. Keuangan",
]

export const statusList = ["Semua", "Aktif", "Cuti", "Pensiun"]

export const golonganList = [
  "Juru Muda (I/a)",
  "Juru Muda Tingkat I (I/b)",
  "Juru (I/c)",
  "Juru Tingkat I (I/d)",
  "Pengatur Muda (II/a)",
  "Pengatur Muda Tingkat I (II/b)",
  "Pengatur (II/c)",
  "Pengatur Tingkat I (II/d)",
  "Penata Muda (III/a)",
  "Penata Muda Tingkat I (III/b)",
  "Penata (III/c)",
  "Penata Tingkat I (III/d)",
  "Pembina (IV/a)",
  "Pembina Tingkat I (IV/b)",
  "Pembina Utama Muda (IV/c)",
  "Pembina Utama Madya (IV/d)",
  "Pembina Utama (IV/e)",
]
